# Generated by Django 5.2.8 on 2025-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Mon Portfolio', max_length=200),
        ),
    ]
