# Generated by Django 5.2.8 on 2025-12-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sitesettings_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
    ]
