# Generated by Django 5.2.8 on 2025-12-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitesettings_hero_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/mobile/'),
        ),
    ]
