# Generated by Django 5.2.8 on 2025-12-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
