# Generated by Django 5.2.8 on 2025-12-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pwa_icon_192',
            field=models.ImageField(blank=True, null=True, upload_to='site/pwa/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pwa_icon_512',
            field=models.ImageField(blank=True, null=True, upload_to='site/pwa/'),
        ),
    ]
