# Generated by Django 5.2.8 on 2025-12-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sitesettings_pwa_icon_192_sitesettings_pwa_icon_512'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(blank=True, default='À Propos de Nous', max_length=200),
        ),
    ]
