# Generated by Django 5.2.8 on 2025-12-27 11:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_service_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_subtitle',
            field=models.CharField(blank=True, default='Je suis toujours ouvert à de nouvelles opportunités.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_title',
            field=models.CharField(blank=True, default='Discutons de votre projet', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
    ]
